### ISSUE TITLE
Doesn't work with WMR

### ISSUE THREAD

**Issue by JustOneMorePaul** [nicoco007/BeatSaberCustomAvatars#1]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/3971828/latest.log)

**Describe the bug**
I've fixed the issue but now don't have custom avatars installed. when i booted after installation i had no control over the game whatsoever. I'm using a WMR and to fix it I had to fresh install and go into the steamapps.vrmanifest and delete the binding file for beatsaber entirely.

**Comment by nicoco007** [comment]
Hey! Sorry for taking so long to get back to you. I unfortunately haven't included default bindings for Windows Mixed Reality controllers so that would explain why it wasn't working.

I have however been able to create a tentative binding for holographic controllers, so if you're using those, could you download and extract [this ZIP file](https://github.com/nicoco007/BeatSaberCustomAvatars/files/3990950/beatsaber_holographic_controller.zip
) and copy `beatsaber_holographic_controller.json` to the `DynamicOpenVR\Bindings` folder in your Beat Saber installation folder (usually `C:\Program Files (x86)\Steam\steamapps\common\Beat Saber`) and tell me if that works?

If that doesn't work or you're using different controllers, could you try following the instructions under "Buttons and/or tracking aren't working properly" in [DynamicOpenVR's troubleshooting guide](https://github.com/nicoco007/DynamicOpenVR/blob/master/TROUBLESHOOTING.md) and let me know if that works?

**Comment by JustOneMorePaul** [comment]
HI! sorry I took so long to get back to you, I haven't been able to get on beat saber. I just tested it and for me the holographic bindings fixed it. only trouble now is that my arms and sabers dissapear when near my face.

**Comment by nicoco007** [comment]
Great! Yeah, that's a known issue. Could you try following the instructions under [Sabers/hands disappear when brought up to the face](https://github.com/nicoco007/DynamicOpenVR/blob/master/TROUBLESHOOTING.md#2-sabershands-disappear-when-brought-up-to-the-face)?

**Comment by JustOneMorePaul** [comment]
I just got on again and tried it out, after a bit of fine tuning I got a good setup at 1.5. thanks for the help!
