### ISSUE TITLE
Avatar list won't load

### ISSUE THREAD

**Issue by ArmyHD** [nicoco007/BeatSaberCustomAvatars#107]
Did I miss something?
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6600371/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10 Pro (version 21H1)
- Headset and controllers: Rift S
- Beat Saber version: 1.16.1

**Describe the bug**
When I open the menu, my avatar list won't load or is stuck with loading. I can't do anything.

1. Installed DynamicOpenVR (manually)
2. Installed DynamicOpenVR.BeatSaber (manually)
3. Installed Custom Avatar (manually)
4. Open Beat Saber
5. Open Custom Avatar menu

**Expected behavior**
Show a list of Avatars.

Things I tried:

- Reinstalled the game
- replaced BSML, SiraUtil with latest version
- reinstalled DynamicOpenVR and Custom Avatar

**Screenshots**
![Screenshot Beat Saber Custom Avatar menu](https://user-images.githubusercontent.com/42937279/120843979-0b815880-c56f-11eb-8ad2-0d1dd4c4f13d.png)

**Comment by nicoco007** [comment]
Oh sorry, that's my bad &ndash; I was told about this a couple of days before you opened this issue and completely forgot to add it to the known issues. I changed a few things related to loading and forgot to add a check if an avatar fails to load, so if that happens, the whole thing breaks. This'll be fixed in the next release (should be coming out within the next few days), but for now, you can remove the avatar that isn't loading properly &ndash; in your case, it's the one called "Komeiji Satori."

**Comment by ArmyHD** [comment]
Oh, thats alright, it's working now :)
