### ISSUE TITLE
Trying to animate the avatar breaks IK and other things

### ISSUE THREAD

**Issue by Erinaaaaaaa** [nicoco007/BeatSaberCustomAvatars#129]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/8036184/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 11 Insider Dev, build 22543.1000
- Headset and controllers: Oculus Rift CV1 + Touch

**Describe the bug**
For some reason, as soon as I add a clip to an animator attached to the avatar, the exported avatar doesn't grip my sabers properly and phases through the floor.

**Steps to reproduce**
1. Prepare your avatar
2. Add an AnimatorController to the model prefab/fbx
3. Add a clip to it
4. Export the avatar
5. Run the game, observe the avatar phasing through the floor

**Expected behavior**
The IK still works and the animation also works.

**Screenshots**
![OculusScreenshot1644438160](https://user-images.githubusercontent.com/20820425/153290006-f33c8b8c-8f8b-49c4-9884-a66a3820ddb8.jpeg)
*Expected behavior - avatar is not animated (note that the skirt clipping through the legs is completely unrelated)*

![OculusScreenshot1644438146](https://user-images.githubusercontent.com/20820425/153290229-12137ead-4b1c-495e-8f2f-4be036e9a333.jpeg)
*Actual behavior - animated avatar*

I can share the project over Discord if needed, as I'm quite confused: it displays properly in the editor.

**Comment by nicoco007** [comment]
This is something I've run into myself and unfortunately just haven't had the time to properly figure out. There's some weird interaction between VRIK and animation controllers but I'm not quite sure what it is. I'll move it up my list of things to do since it's obviously a problem.

**Comment by nicoco007** [comment]
I turns out this is actually due to the way Unity handles animations for armatures marked as "Humanoid." For some reason, even if "Write defaults" is unchecked when inspecting the animation, Unity forces all the Mecanim parameters to 0. One way to solve this is to have the base layer in the animator be a simple T- or A-pose and add an additive layer that has your actual animations. [Here's a ZIP of the ones I've been using](https://github.com/nicoco007/BeatSaberCustomAvatars/files/9398043/DefaultPoses.zip).

There's also an issue with the current version of Custom Avatars where animations will override the finger pose from the editor; that'll be fixed in the next release.
