### ISSUE TITLE
What is when the Avatar doesnt have a .avatar file?

### ISSUE THREAD

**Issue by Sawaya-ui** [nicoco007/BeatSaberCustomAvatars#138]
Hello I had bought an avatar but there is no .avatar file or something. Have looked around on Google etc. how to convert that to an .avatar file or whatever it needs but have found nothing.

**Comment by nicoco007** [comment]
At the moment, this mod uses a custom avatar format. You need to use [the provided Unity project](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/latest) to set up your avatar. Unfortunately the only [guide for creating avatars](https://bsmg.wiki/models/avatars-guide.html) is rather outdated since I haven't had the time to re-write it, but the basic set-up remains the same. You can join the [Beat Saber Modding Group Discord server](https://discord.gg/beatsabermods) and ask in the #pc-3d-modeling channel for help if you're having trouble.

**Comment by nicoco007** [comment]
Closing this since I haven't heard from you in a while. Feel free to open another issue if you're still having trouble!
