### ISSUE TITLE
Import .avatar file back to Unity

### ISSUE THREAD

**Issue by Pawlaklis** [nicoco007/BeatSaberCustomAvatars#142]
Hi! I just wonder if there is a way to import .avatar file back to Unity editor or in any other way modify created avatar?

**Comment by darkkidxin** [comment]
I have the same question too, hope there is a way.

**Comment by nicoco007** [comment]
There are a few tools out there that allow extracting files from Unity asset bundles (which is what `.avatar` files are). That should be a good starting point for your research. I'm not comfortable saying much more than that since the general assumption has always been that `.avatar` files are final and the author does not want them to be modified.
