### ISSUE TITLE
No Avatar Description Script in Project

### ISSUE THREAD

**Issue by Germanreddragon94** [nicoco007/BeatSaberCustomAvatars#150]
I am using Windows 10 and playing with my new Quest 3 without any problems. I play at the moment with the BeatSaber Version 1.29.1.

I want to convert my VRChat Character to BeatSaber and so far everything is working just fine. But now I have the problem I cant find the Avatar Description script. I found it in source but as soon as I copy the Source Folder to my Project I get about 500 errors in Unity Version 2021.3.16f1 which is recommended for me. I dont know what I am doing wrong. So far everything was working.

I tried to use the Version which was recommended from a Video. But if I use the Unity Version 2019.3.15f1 I have a Render Pipeline Error or as I found out a Plugin Loader error. I guess because this old version is no longer supported with this project.

I hope someone know how to solve this issue, it drives me nuts.

**Comment by nicoco007** [comment]
Hey! The [latest release's](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.3.2) Unity project should be working fine with Unity 2019.3.15.

> I found it in source but as soon as I copy the Source Folder to my Project

Do you mean you're copying the entire `Source` folder from this repository into your Unity project? That unfortunately won't work since it contains references to Beat Saber's code that the Unity Editor won't be aware of.

The only set up necessary to get the Unity project working should be:
1. Extract `BeatSaberCustomAvatars-v5.3.2-UnityProject.zip` wherever you want.
2. Copy `FinalIK.dll` and `DynamicBone.dll` from the `Beat Saber_Data\Managed` folder in your Beat Saber install to the project's `Assets\Libraries` folder.
