### ISSUE TITLE
does not initialize with Oculus Store version of Beat Saber

### ISSUE THREAD

**Issue by Uncle-Taco** [nicoco007/BeatSaberCustomAvatars#16]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4336148/_latest.log)

**Desktop (please complete the following information):**
- Operating system: Windows 10 pro
- Headset and controllers: Oculus RIft S

Dynamic Open VR does not initialize. Using the Oculus store version of Beat Saber

**Expected behavior**
I expected it to initialize. Already went through the trroublew sdhotting steps and verrified the files were where they needed to be. The only ones missing were the ones that are created upon initialization.

**Comment by nicoco007** [comment]
According to your log, SteamVR isn't detected. Are you using SteamVR for tracking?

Also, when you say that you expect it to initialize, what do you mean exactly? Is tracking not working in-game?

**Comment by Uncle-Taco** [comment]
I own the oculus version of beat saber. I opened steam vr, but opening beat
saber afterwards didn’t touch steam be at all. When I say I expected
initialization, I meant to see the expected files shown in the
troubleshooting guide to be created. The one shown to be made when the mod
first runs. The files to be manually placed were in their correct spots. I
deleted and replaced them several times to be sure.

**Comment by nicoco007** [comment]
Okay. I guess there's a false positive when checking if SteamVR is running. Could you try these builds and let me know if that fixes it?

* [Custom Avatars](https://ci.gnyra.com/job/BeatSaberCustomAvatars/job/develop/98/artifact/BeatSaberCustomAvatars-d7f5bc4-RELEASE.zip)
* [DynamicOpenVR](https://ci.gnyra.com/job/DynamicOpenVR/job/master/133/artifact/DynamicOpenVR-c309e8e-RELEASE.zip)
* [DynamicOpenVR.BeatSaber](https://ci.gnyra.com/job/DynamicOpenVR/job/master/133/artifact/DynamicOpenVR.BeatSaber-c309e8e-RELEASE.zip)

(unfortunately you need to install all 3 since there are some breaking changes)

**Comment by Uncle-Taco** [comment]
Hello,

I've installed all 3. Was there perhaps a specific order that was
necessary? I opted to instal the aforementioned DynamicOpenVR, then the
beatsaber version, and finally custom avatar. Unfortunately it does not
seem to have worked.

**Comment by nicoco007** [comment]
No, there shouldn't be a specific order in which they need to be installed. Could you attach your latest log with those installed?

**Comment by nicoco007** [comment]
I just released [Custom Avatars](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.0.0-beta.7) and [DynamicOpenVR](
https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.2.0) for Beat Saber 1.8.0. Could you try it out with those and attach your latest log afterwards?
