### ISSUE TITLE
error CS1061

### ISSUE THREAD

**Issue by ErrorUser-not-found** [nicoco007/BeatSaberCustomAvatars#22]
**Describe the bug**
Error on Custom Avatar editor when v.5 editor .dll files are imported into AvatarUnityProject.

**Steps to reproduce**
1. Go to 'AvatarUnityProject'
2. Import 'CustomAvatar.dll'
3. Delete the old 'CustomAvatar.dll'

**Expected behavior**

![problems](https://user-images.githubusercontent.com/25374628/78920702-18eaa200-7a94-11ea-9a5f-0fe51cd14890.PNG)

**Comment by TurtleOne** [comment]
This is the error I mentioned in the other issue. Can confirm this is happening for me on Unity 2018 with same reproduction steps. Additionally re-importing the assets and creating new scene did not fix the issue.

**Comment by ErrorUser-not-found** [comment]
I have made a quick fix https://github.com/ErrorUser-not-found/BeatSaberCustomAvatars.
It's working now, its not a very good fix also.

**Comment by nicoco007** [comment]
@ErrorUser-not-found Thanks for your work, but the root cause of the issue is that the Custom Avatars project is very outdated (it hasn't been updated since 2018). I'm planning on releasing a new version of that project eventually (hopefully alongside the next release, but I can't promise anything), but for now, use **all 3 DLLs** from the Editor ZIP and replace the file `Editor\CompileAvatarWindow.cs` in the Unity project with [this one](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4463388/CompileAvatarWindow.cs.zip).
