### ISSUE TITLE
Cloth physics broken

### ISSUE THREAD

**Issue by ghostiekitty** [nicoco007/BeatSaberCustomAvatars#24]
As the title says, cloth physics got borked with the newest update.

**Comment by fuyushi** [comment]
Can confirm that it is broken for me in the sense that it doesnt respect tethers or bending limitations, resulting in higher stretching and floaty bits.

**Comment by ghostiekitty** [comment]
Yeah.  I didn't know exactly how to word it but that sums it up lol.

**Comment by nicoco007** [comment]
Did this happen when updating to Beat Saber 1.9.0 or was it also an issue in 1.8.0? Also, just to be clear, when you say cloth physics, you mean Unity's built-in cloth system, not Dynamic Bones?

**Comment by ghostiekitty** [comment]
I didn't play 1.8 so I'm not fully sure on that.  Don't think anything really changed in 1.9.  And yes it is the built in cloth physics.

**Comment by nicoco007** [comment]
I'm honestly not sure why this would break since Custom Avatars doesn't touch anything related to Unity's cloth stuff (at least directly). I'll dig into it further when I get the time, although I do have one suggestion: if you haven't already, could you try updating to Unity 2019.3.2f1 when using the Unity project? I believe the game updated to that version when 1.8.0 came out and something may have changed internally.

**Comment by nicoco007** [comment]
As of what I can see on my end, this seems to be indeed caused by the new version of Unity failing to properly load certain avatars compiled with previous versions of Unity. Feel free to reopen this issue or open a new one if this happens when compiling with Unity 2019.3.2f1.
