### ISSUE TITLE
this avatar's face is extremely distorted and warped

### ISSUE THREAD

**Issue by Team-ZzZzZ** [nicoco007/BeatSaberCustomAvatars#27]
I wanted to use an avatar in beat saber but when I looked at myelf in it I saw this
![image](https://user-images.githubusercontent.com/64286760/80258304-ea9ec200-8650-11ea-8996-0cc1cd0c2760.png)
It would seem that part of the face isn't following the rest of the face but rather the feet, now I am aware that parts of an avatar can be improperly assigned if dynamicopenvr.beatsaber is missing but I tried installing it and it didn't help at all, please do help
If it helps to know, my HMD is an oculus rift CV1 and I have a steam installation of beat saber but I normally run it in native oculus mode, however I have tried running it in both and it doesn't make a difference, I'm also running the game off a gtx 1060 6gb but I don't think that has anything to do with it. this issue only occurs with this avatar in particular from my experience but it might occur on others that I haven't tried.
the avatar is supposed to look like this BTW
![image](https://user-images.githubusercontent.com/64286760/80258674-c7284700-8651-11ea-86a4-731183972e33.png)

**Comment by nicoco007** [comment]
It kind of just looks like either the weights are messed up or the face bones aren't parented properly, both of which wouldn't be caused by Custom Avatars but rather by issues with the model itself. Do you know who made this avatar?

**Comment by Team-ZzZzZ** [comment]
It was made by voxian but after some experimenting I discovered that other avatars had a similar problem, also the avatar doesn't look like that entirely. sorry if I didn't explain but the part of by face in the front isn't stretched but simply isn't following the rest of by face but rather either my feet or waist as the stretched front of the face will snap to my face once I move the headset enough to cause the avatar to sidestep instead of tilt, other avatars will sometimes have a component on the face move like this and it sounds like the issue on the front page that talks about needing the .beatsaber installed but I have it and the "tracker roles" still don't seem to be assigned properly.

**Comment by Salverin** [comment]
Noticed this issue as well, not sure if it'd be the model though, since it worked up until v1.8.0b2.

**Comment by Team-ZzZzZ** [comment]
I don't think it's the model's fault considering some other models have a similar problem to a lesser degree (than horrifying distortion)

**Comment by nicoco007** [comment]
Unfortunately I haven't been able to reproduce this issue on my end with any of the avatars I have. Would either of you be willing to share an avatar that exhibits this issue here so I can check it out?

**Comment by Team-ZzZzZ** [comment]
[foxtaur avatar.zip](https://github.com/nicoco007/BeatSaberCustomAvatars/files/4587839/foxtaur.avatar.zip)

This is the avatar I showed in the screenshot above

**Comment by nicoco007** [comment]
Based on what I'm seeing, the animator on that avatar is misconfigured. Since the avatar used to work properly, I'm guessing this happened because the Beat Saber devs updated from Unity 2018.4.4f1 to 2019.3.2f1 during the 1.8.0 update and something changed internally. There is unfortunately nothing I can do on my end to fix this. I believe the avatar simply needs to be recompiled using Unity 2019.3.2f1, but that requires the source files.

**Comment by nicoco007** [comment]
After further investigation, it does indeed seem to be a version incompatibility. There is unfortunately nothing I can do about this since Unity is just giving me garbage information when loading certain older avatars. Feel free to reopen this issue or open a new one if this happens when compiling with Unity 2019.3.2f1.
