### ISSUE TITLE
Finger Tracking

### ISSUE THREAD

**Issue by kanauru** [nicoco007/BeatSaberCustomAvatars#29]
Finger tracking doesn't appear to be working except for the default full body avatar.

How do we setup our avatar for finger tracking or is it supposed to automatically do it if the armature is setup properly?

**Comment by nicoco007** [comment]
Unfortunately finger tracking has to be configured when creating the avatar. Doing it automatically while being compatible with every single model out there would be nearly impossible due to the different ways bones might be set up position- and rotation-wise, so it's easier to just have it custom-made for each avatar.

Setting up finger tracking is a rather tedious operation for the time being because I haven't really taken the time to figure out a better way just yet (I'm open to suggestions though). I'll eventually make a full guide to this, but basically you just need to add the `PoseManager` script (included in the new editor DLL, check [this comment](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/22#issuecomment-612212048) to get it working for now; note that you will need to migrate to the new `VRIKManager` script as `IKManager` and `IKManagerAdvanced` have been deprecated) to your model (i.e. the same GameObject as `IKManager`). Then, use the "Save Open Hands Pose" and "Save Closed Hands Pose" to save the poses of the fingers. You can check the poses were saved properly by using the "Apply Open Hands Pose" and "Apply Closed Hands Pose" buttons. There is currently no way to undo/redo when using the "Apply" buttons so be careful!

The way I usually set it up on my avatars is as follows:
1. Set up avatar with closed hands as usual
2. Add a copy of **only the model** next to it (but not under the avatar's Game Object) with open hands
3. Add the PoseManager script to the open hands model, save the open hands pose, then move the script to the actual avatar's model (with closed hands) and save the closed hands pose
4. Check that both were saved properly using the "Apply" buttons

Let me know if anything's unclear.

**Comment by kanauru** [comment]
I was wondering what that script was for haha.

It works!

Thanks!

**Comment by nicoco007** [comment]
Great! Since you were able to get it working, I'll close this issue.
