### ISSUE TITLE
No Avatar black box

### ISSUE THREAD

**Issue by GucciiB** [nicoco007/BeatSaberCustomAvatars#39]
When "No Avatar" is selected, a big black box covers most of the screen and makes it impossible to see anything. However the menu's are still accessible and when changing avatars, it works normally. Unfortunately the default is "No Avatar" so might cause a lot of confusion like it did with me.
![unknown](https://user-images.githubusercontent.com/64643385/83966757-1bab1d00-a8b4-11ea-86e8-bfa699d02591.png)

**Comment by nicoco007** [comment]
Yeah, it's a weird issue with the mirror when it has nothing to reflect that I've yet to figure out. IIRC it only happens when there's more than one camera rendering (e.g. when Smooth Camera or CameraPlus is enabled), which is why I haven't really taken the time to look into it, but it definitely needs to be fixed.

**Comment by nicoco007** [comment]
Beta 8 was just released and should fix this issue. If you are still having problems, feel free to reopen this issue or create a new one.
