### ISSUE TITLE
Head invisible by CameraPlus in 5.0.0-beta8

### ISSUE THREAD

**Issue by superjeng1** [nicoco007/BeatSaberCustomAvatars#47]
**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers: HTC Vive

**Describe the bug**
Some models I am using at version 5.0.0-beta7 is working properly with CameraPlus, but now, some model appears headless to CameraPlus, and the Show/Hide avatar option in CameraPlus isn't working either.

**Steps to reproduce**
1. Get this model: https://modelsaber.com/Avatars/?id=1564098907&pc
2. Open the game
3. Do FBT calibration
4. The avatar appears headless to CameraPlus

**Expected behavior**
The full avatar can be seen with CameraPlus

**Comment by superjeng1** [comment]
Maybe related to #41

**Comment by superjeng1** [comment]
Ok, I decided to dig around the issue pile a bit more, and I found [this comment](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/43#issuecomment-660763467) from one of them, and I tried the version of CameraPlus provided, and it worked.

**Comment by nicoco007** [comment]
Sorry about that, I should have mentioned this is a known issue in the release notes; I've now added it. Just keep in mind that the version from #43 is unofficial and isn't supported by the current Camera Plus maintainer. An official fix will be coming soon.

Closing this since you were able to solve the issue.
