### ISSUE TITLE
Readding Avatar Head in First Person View?

### ISSUE THREAD

**Issue by SteffoSpieler** [nicoco007/BeatSaberCustomAvatars#49]
**Is your feature request related to a problem? Please describe.**
An older Version of this Plugin had the ability to see the Avatar Head in First Person View. I kinda liked it and I am sad, that you can't see the Head in First Person View anymore.

**Describe the solution you'd like**
Maybe adding a button to the "Avatars" Page to toggle the Head in First Person View?

**Describe alternatives you've considered**
(There's nothing I can do, soo...)

**Comment by nicoco007** [comment]
Sorry I took so long to answer, I somehow missed this in my notifications.

I'm a bit confused because I don't recall this ever being a feature. The things that aren't visible in first person (which is often the head but can also be other things) are set up by the person who created the avatar, usually because it would cause issues if it were visible.

While adding a setting like this is possible, I'm not sure I understand why you would need it. Could you explain what you mean exactly by "seeing the avatar head in first person" ? From what I can tell, you can't really see the head in first person except maybe the tip of the nose and the hair; am I missing something?

**Comment by SteffoSpieler** [comment]
In an older version I was able to see the muzzle of [the character I play](https://modelsaber.com/Avatars/?id=1575334977&pc). But after an update of this plugin (and beat saber) I couldn't see the muzzle anymore.

I thought that was a bug and I just let it like this. But now I thought of it again and would love to see the muzzle of the character again, since I got used to it.

**Comment by nicoco007** [comment]
Ah okay, I see. I'll definitely add this, probably under the "Avatar Specific" tab in settings.

**Comment by nicoco007** [comment]
I've added a setting called "Ignore Exclusions" under the "Avatar Specific" settings tab. It'll be included in the next release.
