### ISSUE TITLE
Custom Avatar Mod don’t work

### ISSUE THREAD

**Issue by Luciankale** [nicoco007/BeatSaberCustomAvatars#53]
**Desktop**
- Operating system: Windows 10
- Headset: Oculus Rift S

**Describe the bug**
The Custom Avatar Mod doesn’t work, I don’t know why because I did everything right.
It doesn’t shows up in the Beat Saber Mod Menu.

**Comment by nicoco007** [comment]
Could you please attach your latest log? It's the file called `_latest.log` inside the `Logs` folder of your Beat Saber install.

**Comment by Ninj4x** [comment]
> Could you please attach your latest log? It's the file called `_latest.log` inside the `Logs` folder of your Beat Saber install.

this is the exact problem (log below)

[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5054553/_latest.log)

**Comment by nicoco007** [comment]
@Ninj4x Looks like you're missing DynamicOpenVR. You can download it from [DynamicOpenVR's releases page](https://github.com/nicoco007/DynamicOpenVR/releases). Note that you only need DynamicOpenVR, **not** DynamicOpenVR.BeatSaber.

@Luciankale since you did not upload a log, I unfortunately cannot know for sure what might be wrong, but since you're running an Oculus headset, you might be running into the same issue as #46. Could you try [the version I posted in this comment](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/46#issuecomment-662191487)?

**Comment by Ninj4x** [comment]
> @Ninj4x Looks like you're missing DynamicOpenVR. You can download it from [DynamicOpenVR's releases page](https://github.com/nicoco007/DynamicOpenVR/releases). Note that you only need DynamicOpenVR, **not** DynamicOpenVR.BeatSaber.
> 
> @Luciankale since you did not upload a log, I unfortunately cannot know for sure what might be wrong, but since you're running an Oculus headset, you might be running into the same issue as #46. Could you try [the version I posted in this comment](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/46#issuecomment-662191487)?

That was definitely the case, Thank you

**Comment by nicoco007** [comment]
Since I haven't gotten any news in 2 weeks, I'm going to assume this is no longer a problem. Feel free to open a new issue if it still is.
