### ISSUE TITLE
[Feature] Multiplayer Compatibility

### ISSUE THREAD

**Issue by Zingabopp** [nicoco007/BeatSaberCustomAvatars#54]
**Is your feature request related to a problem? Please describe.**
Currently, CustomAvatars doesn't seem to have a way to be integrated into a mod like Multiplayer. Andruzz has a workaround using a private CustomAvatars build, but it's outdated and it would be nice if the functionality needed for Multiplayer was available in the official mod.

**Describe the solution you'd like**
From what I've seen looking at Andruzz's private build, CustomAvatars would need to include:
  * The method to spawn avatars not linked to the player from another mod.
    * Given an IAvatarInput implemented by the other mod to keep the position updated?
  * Access to the local player's avatar positions (Multiplayer uses that to send position data to other players).
  * [Optional] Public list of available avatars - Not necessary if you can spawn an avatar using a file string, but could be nice for UI purposes.
    * Maybe a static/singleton class that contains info about the avatars
    * Also consider that Multiplayer will download avatars if another player has one from model saber that the player doesn't have.

**Comment by nicoco007** [comment]
I've actually been slowly working towards a better external API of sorts. Having a concrete list of things to do regarding it makes it a lot easier, so thanks for this! Here's the status so far:

- **Loading/spawning additional avatars:** This is mostly covered by the [BeatSaberCustomAvatars.ApiSample](https://github.com/nicoco007/BeatSaberCustomAvatars.ApiSample) project, although it doesn't work 100% properly yet.
- **Local player's position:** This is the most annoying one, mostly because of local room setup and how calibration works. I'm working on some changes to `VRPlayerInput` (the player avatar's `IAvatarInput`) that will make it possible to get calibrated tracking data without applying local setup stuff. I'm also working on a minor overhaul of the tracking system which should hopefully make things a bit easier to understand.
- **List of available avatars:** Most of this is stored in `PlayerAvatarManager` so it'd be pretty trivial to expose publicly.

This'll probably not come with the next release (RC 1) since there's some bugfixes I want to get out ASAP, so it'll most likely end up in the release after that.

**Comment by nicoco007** [comment]
I've shipped the initial version of this in v5.0.0 and I've updated the [sample project](https://github.com/nicoco007/BeatSaberCustomAvatars.ApiSample) to use the new, public `VRPlayerInput` class. I'm not exactly sure of the state of modded multiplayer right now, so let me know if this works!

**Comment by nicoco007** [comment]
I think I'll wait until Zingabopp/MultiplayerExtensions#29 is merged before closing this to make sure the API makes sense and works as expected.

**Comment by Goobwabber** [comment]
The CustomAvatars feature for MultiplayerExtensions [(Zingabopp/MultiplayerExtensions#29)](https://github.com/Zingabopp/MultiplayerExtensions/pull/29) was moved to [Goobwabber/MultiplayerAvatars](https://github.com/Goobwabber/MultiplayerAvatars). Also, the API is great!

**Comment by nicoco007** [comment]
Great, thanks for letting me know! I'll close this issue but if you ever have problems feel free to open a new one.
