### ISSUE TITLE
Still can't see avatar list.

### ISSUE THREAD

**Issue by MorgieDeAnne** [nicoco007/BeatSaberCustomAvatars#60]
I saw a previous post about this and followed instructions and re-installed but I am still having the same issue of not being able to see my avatars list. I read over the trouble-shooting page and all the files appear but still not showing in game.

**Comment by nicoco007** [comment]
Could you please attach your latest log? It's the file called `_latest` in the `Logs` folder of your Beat Saber installation.

**Comment by MorgieDeAnne** [comment]
[_latest avatar log.txt](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5121101/_latest.avatar.log.txt)

**Comment by danagin** [comment]
Just checking in, I'm having the same issue. Tried rc1 and rc2 posted in issue 58. I can post logs later if that helps.

**Comment by efluffy** [comment]
Same issue effecting me. Can see custom avatar settings on the left -- but no avatar list in the center. Attached latest log.
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5159437/_latest.log)

**Comment by nicoco007** [comment]
@MorgieDeAnne Unfortunately I need to full log (i.e. the one directly inside the Logs folder, not inside the Custom Avatars folder) since errors only show up in the full log.

@danagin If you could also upload your log that would help me make sure there aren't multiple underlying problems!

@efluffy Looks like you've accidentally downloaded the still broken version from my first comment in #58. Could you try the version that I posted [in my second one](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/58#issuecomment-676755378)?

**Comment by djicode** [comment]
It's working for me with: https://github.com/nicoco007/BeatSaberCustomAvatars/issues/58#issuecomment-676755378
The feet are still an issue. Has anyone having the issue manually updated dependencies to the latest versions?
