### ISSUE TITLE
Show warning if BeatSaberCustomAvatars is installed without DynamicOpenVR

### ISSUE THREAD

**Issue by Stevoisiak** [nicoco007/BeatSaberCustomAvatars#63]
**Is your feature request related to a problem? Please describe.**
A common issue I see, (and have run into myself), if BeatSaberCustomAvatar is installed without the required DynamicOpenVR, the avatars button will be missing from the mod list, without any indication for the user of what went wrong.

**Describe the solution you'd like**
If DynamicOpenVR is not installed, include the Avatar button in the mod list, but show an error when the button is clicked to tell the user how to fix the issue.

"_Error: DynamicOpenVR is required to use BeatSaberCustomAvatar. Please close the game and install it._"

**Describe alternatives you've considered**
An error message on startup for Beat Saber would also work.

**Comment by nicoco007** [comment]
Unfortunately there is no elegant way of doing this. BSIPA deals with dependencies so none of my code gets executed if a dependency (in this case, DynamicOpenVR) is missing. I could technically make it an optional dependency, but that would be pretty ugly and implementing something like that defeats the whole purpose of BSIPA's dependency system. It would probably make more sense to implement a feature like this in BSIPA/ModList or (to a lesser degree) BSML that applies to all mods.

This will no longer really be an issue once Custom Avatars is back on ModAssistant (as long as you use it) since that fetches dependencies automatically. That will take a bit of time though because I can't upload betas/release candidates to BeatMods due to weird limitations.
