### ISSUE TITLE
Headset/controller lags when I open Avatars 

### ISSUE THREAD

**Issue by gadgetgurlvr** [nicoco007/BeatSaberCustomAvatars#64]
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5145083/_latest.log)
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

**Desktop (please complete the following information):**
- Operating system: Windows 10
- Headset and controllers:  Valve Index

**Describe the bug**
When I go into Avatars, my headset and controllers get extremely laggy. Once I get out of Avatars the lag goes away. 

**Steps to reproduce**
1. Go to Mods
2. Click on Avatars
3. once I'm in there the headset just lags, I can barely control my controller to click any options or even trying to exit.

**Expected behavior**
Does not happen when I am using any other mods like Custom Sabers 

**Screenshots**
none taken

**Comment by gadgetgurlvr** [comment]
I recorded the lag, you can see it here: https://www.youtube.com/watch?v=q3mZ2_qoOfA

**Comment by nicoco007** [comment]
Sorry about the long wait, I've been busy with other external stuff.

Unfortunately I'm not really sure what to tell you here because there aren't any errors related to Custom Avatars in the log you provided. Do you remember if you entered the Avatars menu during that session? I'm guessing you didn't because I don't see the logs that would lead me to believe you did, but I could be wrong or something may be preventing them from showing up; if you didn't, could you upload the log of a session where you entered the menu?

**Comment by gadgetgurlvr** [comment]
I thought I did, but I could be wrong. Kinda new to the whole avatar thing. I'll try again tonight and send a new log.
