### ISSUE TITLE
Avatar select menu not working on 1.11.0

### ISSUE THREAD

**Issue by MisterMIntBoy** [nicoco007/BeatSaberCustomAvatars#67]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

**Desktop (please complete the following information):**
- Operating system: Windows 10 Pro
- Headset and controllers: Valve Index

**Describe the bug**
The newest version has been installed (I believe 5.0.0 candidate 1), and since the update, when I select the avatar menu under the mods, the menu on the right where the avatars are normally displayed just shows leaderboard statistics, and the back arrow to leave the menu has disappeared, so to get out of the menu, you have to completely restart the game.

**Steps to reproduce**
1. Launch game
2. Select mods tab on the left menu
3. Select 'Avatars'
4. ???
5. Profit?

**Expected behavior**
I expect the menu to work, like in previous version of the game and mod.

**Screenshots**
None at this time, will attach screenshot/ link to video when I have the time to get it.

**Log File**
[Here is the log file from the latest time launched.](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5213606/_latest.log)

**Comment by nicoco007** [comment]
Looks like the same issue as #58. Could you try the version that I posted in [my comment over there](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/58#issuecomment-676755378)?

I'm closing this issue since #60 is about the same problem. Please follow up there if you're still having trouble after using the version I linked above!
