### ISSUE TITLE
[Feature] Would love an option to negate / customize hand offsets / angles

### ISSUE THREAD

**Issue by tehbiga** [nicoco007/BeatSaberCustomAvatars#71]
**Is your feature request related to a problem? Please describe.**
I've been customizing my controller angles since before Beat Saber added the feature in to the base game. Once thing I've always noticed is that the avatars wrists are essentially broken by these settings.
It also seems to cause the arm IK to do some weird things such as bend the elbows into the chest.

**Describe the solution you'd like**
I'd love an option to negate custom controller offsets or just set custom rotation and position offsets in CustomAvatars to manually negate the visual effect customized saber offsets cause.
The hands may no longer "hold" the sabers in game, but then the IK would perform much better and look less crazy when playing.

**Describe alternatives you've considered**
I tried reducing my custom offsets to compromise between look and feel when playing, but I've really grown accustomed to my play style and just deal with the avatars wrists looking broken.

**Comment by nicoco007** [comment]
I actually just discussed this exact issue with someone else in #68. Are the wrists broken if you try the _Template – Full Body_ avatar? If not, the issue you're seeing with other avatars is caused by a lot of avatar creators not taking into account that controllers (and therefore sabers) are held at a slight angle (around 30°) and not completely perpendicular to the fingers. While adding a manual offset in-game is definitely possible, it doesn't make much sense for me to spend time on an issue that can be fixed with a minor adjustment on the creator's side (and therefore shouldn't really exist in the first place). It would also make the in-game settings menu even more cluttered than it already is.

**Comment by tehbiga** [comment]
Most of the issue is definitely the avatar. The full body template handles it much better, but with my custom 45 degree X offset the elbows are pretty close to the body. Honestly not a big deal so maybe I'll try to fix the model if that is even possible (I'm not the author).

**Comment by nicoco007** [comment]
Sorry, I completely forgot to reply to this. Since this is indeed an issue with how avatars are set up, I won't be adding this feature (at least for the time being). There's already a lot of stuff in Custom Avatars that corrects bad avatar setups and I have to draw the line somewhere or else I'll end up with more corrections than actual features.

Regarding fixing the avatar(s) you want to use, it might be easier to contact the original author. I believe it is possible to extract the avatar bundles created when exporting but they're a bit weird to work with.
