### ISSUE TITLE
Hand and Head Calibration

### ISSUE THREAD

**Issue by Artremiss** [nicoco007/BeatSaberCustomAvatars#72]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5455653/_latest.log)

**Desktop (please complete the following information):**
- Operating system: [e.g. Windows 10, Ubuntu 18.04] Windows 10
- Headset and controllers: [e.g. Oculus Rift, HTC Vive, Valve Index] Oculus Quest

**Describe the bug**
A clear and concise description of what the bug is. If your issue occurs with a particular avatar, please add a link to where you found it or attach it; **please do not attach the avatar file to this issue if you did not create it**.

I'm having issues with getting any avatar to work properly. I've tried using a few different avatars ([Holo](https://modelsaber.com/Avatars/?id=1552959303&pc), [Miku](https://modelsaber.com/Avatars/?id=1564625718&pc), and [Ruby](https://modelsaber.com/Avatars/?id=1572761375&pc)) and they all seem to be having issues. It seems like for some reason the shoulder's of the models are stiff and stuck, while the forearm is okay and moves properly. When I try calibrating my arm length, I also notice that my HMD is significantly higher than the model's and when I enable first-person mode the inside of the head model is visible whenever I bend down a bit. And when I try to move my hand, the length of the arm is significantly shorter on the model than it really is. I have a link to a [VOD ](https://www.twitch.tv/videos/785029089) (At around 4:30 you can see it clearly) I just streamed to show the issue (still setting up streaming so I may have screwed up somehow).

**Comment by nicoco007** [comment]
Thanks for the video; it's very useful to actually see the problem! I've checked out the 3 avatars you linked and I didn't really notice any issues with Miku but I did with Holo and Ruby, although not as bad as what you're seeing. It seems to be that the avatars' hand orientation wasn't detected properly when exported which causes the elbows to be too high. This problem is made more obvious when there is an issue with scaling, which you seem to be encoutering as well. Unfortunately, there isn't much I can do about the hand orientation since that needs to be manually set when creating the avatar if it isn't detected properly, but we should be able to solve the scaling problems.

The avatar arm length seems to be detected properly so I'm guessing there might be something wrong with the way the player's arm span is measured. Does your measured arm span make sense? It should be roughly the same as your full height (usually a few centimeters less). Also, if you spread your arms, are the avatar's arms straight or do they bend? Double-check that you're actually using the "Arm Span" resize mode before doing this.

As for your HMD being higher than the avatar's head, that's also most likely related to scaling since most avatars are configured to have their feet stay on the ground even if the HMD is out of reach. Does it happen if you use the "Height" resize mode? Have you turned on the "Enable Floor Adjust" setting?

**Comment by Artremiss** [comment]
From what I saw, the arm length was pretty accurate when it came to the distance (~1.7-1.8m when I am 5'11" height) although the reading does seem to vary when I do it multiple times (range from 1.5-1.8m at the same position). It seems like when I measure the character's hands are higher than they are IRL (closer to head height rather than shoulder) for all models that I try. Even the template has the issue a bit (although the scaling problem doesnt appear). And yes I am using the "arm span" option.

When I turn on the height option, for some reason the character model becomes dramatically smaller and my arm size becomes drastically smaller. I have all the floor settings options on, and disabling any of them doesn't help. 

After some testing, I realized that beat saber's automatic height was off (1.5m), and after manually re calibrating it to 1.7m it fixed the head displacement issue and arm aiming to the head. After some more testing, it seems to have massively fixed the problem. I still get some random hair and face displacement if I move my head too quickly or in certain positions, and my hands are still slightly off the sabers when I fully extend. And movement displacement is sometimes a bit messed up. But this maxes it wayyy better.

With this fix, without my floor adjust setting on my model was permanently crouched down, but with it on it fixed it and made it nearly perfect (asides for the minor issues I mentioned.

For my Height resize mode, I still noticed the same issues. It was configured properly to my head this time (unlike previously with the height unadjusted), but the model was scaled significantly smaller and the arm size was extremely small. Fortunately with the arm resize mode, it solved the scaling issues and made it significantly better to play with.

So I guess the main culprit was beat saber's height setting. For some reason the auto setting messed up, and manual readjustment fixed most of my issues. I still don't know what is up with those other minor problems, but its leagues better than it was before and first-person mode is actually playable now.

**Comment by nicoco007** [comment]
Having the wrong height set definitely breaks a lot of things! I completely forgot to ask about that so I'm glad you thought about it. I should probably add a message that tells the player that automatic player height isn't recommended exactly because of the problems you encountered.

Could you explain a bit more what you mean by "random hair and face displacement" ? If I'm interpreting it right, I'm guessing it might be an issue with the avatar's model, but I could be wrong.

Something that might help with the sabers being slightly off when you fully extend your arms is to aim the controllers outwards while calibrating (i.e. if you were holding sabers, they would be extending outwards parallel to your arms). I'm not sure why you're getting varying results though; I've tried it a few times now and it seems repeatable on my end.

The arms being smaller when you resize by height is most likely because some avatars have height to arm span proportions that are different than the average human. I noticed this specifically on the Holo avatar which is much taller than its arm span.

Hopefully this helps!

**Comment by Artremiss** [comment]
> Could you explain a bit more what you mean by "random hair and face displacement"
So whenever I move my head too quickly in a direction, I can see the model's hair and sometimes (inside) face for a few moments. I think it may be somewhat model dependent, because the Ruby model's hair flows and is much more in view than the holo model. But I still do sometimes get the issues with holo despite her rigid hair, although much less often, and for shorter bursts (just on the edges of my vision). Same thing with the face issue, moving down rapidly I sometimes see inside or above my character's face for a few split seconds.

Hmm... I do think I normally pose like that but I still get the issue. I also have a different grip style than normal (my finger goes over the controller so it is shorter in my hand) but I don't think that should matter if I maintain the grip style all the time. I also did try experimenting using the standard grip, but the saber issues still occurs. And I have no idea why the results vary... some times it is consistent, but randomly it would vary, even when I hold the same position. Sometimes restarting BS can change my consistency, so idk...

That's what I thought too, but from what I see it occurs for all 3 avatars I linked, not just holo.

**Comment by nicoco007** [comment]
I remember someone having a similar issue with a model where the face didn't quite follow the HMD. I eventually concluded that it was an incompatibility between the version of Unity used to export the model (most likely 2018.1.6f1 since that's what most people use up to this day) and the version of Unity that Beat Saber now uses (2019.3.15f1 at the time of writing). That might be why you're seeing weird issues with Ruby.

I'm still not sure what could be causing inconsistent arm span measurement. However, I think the arm span measurement might be slightly off based on how the saber is being held by the avatar (i.e. how parallel it is to the arm when said arm is stretched out). I'll have to look into it.

**Comment by nicoco007** [comment]
Sorry, I've been busy and wasn't paying attention. I've been looking into better ways of measuring arm span but I'm not sure what's the best way just yet.

**Comment by nicoco007** [comment]
I've done a bit more fiddling and I've come to the conclusion that arm span is essentially impossible to get right 100% of the time because of two things that would have to match up perfectly with the player:

1. The ratio between the lengths of the arm and hand of the avatar
2. The rotation of the controller/saber in the avatar's hands

The current arm length calculation will always try to get the maximum possible arm span (i.e. when the arms and hands are completely stretched out to either side of the body), which sometimes causes avatars to bend their arms if they're in any other position if the two things listed above don't match up with the player. I've made some changes to the arm span measurement in the Avatars menu that hopefully make it a bit more reliable, but I was never able to reproduce your issues with inaccurate measurements so I can't promise anything.

If you still have concerns, please let me know!
