### ISSUE TITLE
Finger tracking?

### ISSUE THREAD

**Issue by Protected** [nicoco007/BeatSaberCustomAvatars#76]
There's a mention to finger tracking in an old changelog, but my fingers don't track in-game. What's the procedure to get finger tracking to work in an avatar (if at all possible)?

**Comment by MoePus** [comment]
Add the `PoseManager` to avatar (in unity avatar project)

**Comment by MoePus** [comment]
wikis guide is outdated. but the new guide is not done...
first of all, you need replace the customavatar.dll in your unity project with [this from release](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/download/v5.0.1/BeatSaberCustomAvatars-v5.0.1-Editor.zip)
and then, there would be lots of suffering before you can export an avatar...

**Comment by Protected** [comment]
Exactly; I mention this in my other ticket. Replacing the dll introduces a lot of errors.

**Comment by lithiumfox** [comment]
Not going to lie, I managed to get it to work and I have 0 idea how. :| (mostly cause the .dll files don't seem to be included with almost any file structure, i randomly found them in a file somewhere, and whatever)

And somehow I managed to BOTH break my SteamVR shaders (hahahaha cameramode: raw for sims), and get finger tracking to work before I figured out full body tracking. Which, also, needs some _heavy_ changes in the IK to stiffen up some areas like neck movement and body movement, imo. 

HOWEVER, on a side note, Finger Tracking is pretty easy:

Add PoseManager (using the Unity project file in the release files for unity version 2019.3.15f1), move your armature for one of your hands, copy that hands pose using the respective button, then save it. Then do the same for closed. Its actually... realllly easy to do, just have to know how to move bones well enough. I managed to get mine to look like its actually holding the sabers pretty well.

However, I can't get FBT to work it seems, at least on my current avatar, I think I named something wrong. But otherwise, yeah. Super easy to get fingers to work, actually.

**Comment by Protected** [comment]
I've had no issues with full body tracking in the 2018 project! By which I mean leg and waist roles. Excelent work from nico and predecessors there.

I agree that IK parametrization is difficult. I can't get the elbows to work right.

You seem to be saying I (eventually - when I can get the 2019 project to work) need to pose all the hands again for finger tracking, which is a bummer. It was hard work doing it with shape keys... (I'm happy with the current state of my closed hands using shape keys)

I don't know how to port the project to the 2019 version without things breaking, which is my major problem.

FinalIK.dll and DynamicBone.dll can currently be found in Beat Saber/Beat Saber_Data/Managed .

**Comment by lithiumfox** [comment]
> You seem to be saying I (eventually - when I can get the 2019 project to work) need to pose all the hands again for finger tracking, which is a bummer. It was hard work doing it with shape keys... (I'm happy with the current state of my closed hands using shape keys)

This is correct. And The reason is because shape keys don't correctly animate the bones between open and closed.

And it's so much easier to do than shape keys, imo.


as for the full body tracking I still don't know what the heck happened. I managed to fix it through a combination of just messing with some settings and it resolved itself. I believe the issue was a small bug with The project where the left leg and right leg were not automatically generating a target when doing the avatar export, as I noticed initially when I would play in unity it wasn't being generated. However, what happened was I added a left leg and right leg Target in final IK to make sure that the left leg and right leg were at least working within the unity editor and then after I removed it it started out of generating again so I don't know what that's about.

**Comment by nicoco007** [comment]
Sorry for the delayed reply! I've replied to #75 on how to get the new DLLs set up. I don't currently have a guide on how to use PoseManager, but the instructions that @MoePus and @lithiumfox have given are good.

**Comment by Protected** [comment]
OK, I removed the shape from the mesh, added the pose manager, and saved open and closed poses for both hands. When I run the game, the avatar holds the saber using the new closed hands pose from the pose manager, however it still doesn't detect my fingers/use the open hands pose. Am I missing anything?

lithiumfox, could you share your IK tweaks? Might help me with similar troubles.

**Comment by nicoco007** [comment]
You need [DynamicOpenVR.BeatSaber](https://github.com/nicoco007/DynamicOpenVR/releases) for finger tracking to work in-game. Note that it is only tested with SteamVR and some people have reported various issues (including completely breaking their Beat Saber or Steam install) that I unfortunately cannot reproduce.

**Comment by Protected** [comment]
Confirmed working, thanks! As a suggestion, it would be nice to have a setting in the menu or button binding to enable/disable finger tracking once it's working.
