### ISSUE TITLE
Not compatible with vive tracker 3.0?

### ISSUE THREAD

**Issue by Veverus** [nicoco007/BeatSaberCustomAvatars#99]
I've been trying to use 3.0 vive trackers with this mod, but to no avail. I believe I've done everything I need to do to get this to work, but to no avail. I've tried getting help from people, but no one seems to know what the issue is or how to fix it. When I calibrate full body in the custom avatars menu, my feet and ankles are all twisted. I've tried changing tracker rotation, and no change. It seems like the feet are rotated 90 degrees on the x and y axis, but I'm not sure on that. It tracking fine positionally, but as stated previously, the rotation seems to be all messed up. The same issue occurs on all avatars that I've tried.
![20210404155243_1](https://user-images.githubusercontent.com/36616857/113618174-e8910180-961c-11eb-846a-e113a2b8c7e1.jpg)
![20210404223154_1](https://user-images.githubusercontent.com/36616857/113618175-e9299800-961c-11eb-8d8c-02808c2fdb03.jpg)

**Comment by Chemuhk** [comment]
I'm on the 2.0 trackers and have precisely the same issue - the feet are twisted 90 degrees, both pointing the same direction. I have the trackers correctly configured in SteamVR and have tried unbinding, rebinding, relaunching, uninstalling and reinstalling the mod. No luck.

**Comment by Veverus** [comment]
If you would like to get in contact on discord, we could try troubleshooting things together. My discord is Vevvy#1234.

**Comment by UltimasDragon** [comment]
I don't know if this will help, but I recently just upgraded to the index and also vive 3.0 trackers.
I was having more or less the same issue.
What solved it was, originally in the steam VR room set up I had the room 180 degrees from what I was facing in beat saber (with the in game room setting set to 180 compensate.)
So what I'm guessing fixed it was I reset up the room in steam VR and fixed the room orientation so that it matched where I was facing in beat saber.

I think what's going on is the trackers naturally orient themselves to SteamVR and assume that w/e game you're in will be the same.

**Comment by Veverus** [comment]
That actually did the trick, UltimasDragon. Thank you so much!
